# allows you to define your content collections
collections_config:
  # "pages" is the name of a collection and represents
  # the default content under "content"
  pages:
    # the pages in this collection will be rendered to your site's output
    output: true

# lets you define the locations of different types of files in your site
paths:
  data: data
  # "collections" are located in the "content" directory
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Europe/Berlin
